### ISSUE TITLE
Failed to load native library:jansi-2.4.0-b00c64e8b23a020c-jansi.dll. osinfo: Windows/x86_64

### ISSUE THREAD

**Issue by asimplepeople** [apache/maven-mvnd#828] opened 2023-03-26 15:24 UTC
PS C:\Windows\System32> mvnd --version
Failed to load native library:jansi-2.4.0-b00c64e8b23a020c-jansi.dll. osinfo: Windows/x86_64
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\???\AppData\Local\Temp\jansi-2.4.0-b00c64e8b23a020c-jansi.dll
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.fusesource.jansi.internal.CLibrary.isatty(I)I [symbol: Java_org_fusesource_jansi_internal_CLibrary_isatty or Java_org_fusesource_jansi_internal_CLibrary_isatty__I]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:53)
        at org.fusesource.jansi.internal.CLibrary.isatty(CLibrary.java)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:102)

**Comment by asimplepeople** [comment] 2023-03-26 15:25
my windows user is 谢兆辉 chinesename

**Comment by asimplepeople** [comment] 2023-03-26 15:25
PS C:\Windows\System32> java --version
openjdk 20 2023-03-21
OpenJDK Runtime Environment (build 20+36-2344)
OpenJDK 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)

**Comment by ppalaga** [comment] 2023-03-29 13:25
Perhaps a duplicate of https://github.com/apache/maven-mvnd/issues/571? - that one suggests to upgrade to a newer Java 11 version. You say you have openjdk 20. Does it work with an older JDK version, such as 17 or 11 for you?

**Comment by gnodet** [comment] 2023-05-18 05:47
Duplicates #793

**Closed by gnodet** 2023-05-18 05:47 UTC
