### ISSUE TITLE
The built-in 4.0.0 version of maven will invalidate the flatten-maven-plugin plugin

### ISSUE THREAD

**Issue by meiMingle** [apache/maven-mvnd#773] opened 2023-01-13 09:14 UTC
mvnd:1.0.0-m1，
flatten-maven-plugin:1.3.0

mvnd clean install -X

> [ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.3.0:clean (flatten.clean) on project cloud-fastpaypc: Execution flatten.clean of
goal org.codehaus.mojo:flatten-maven-plugin:1.3.0:clean failed: Unable to load the mojo 'clean' (or one of its required components) from the plugin 'or
g.codehaus.mojo:flatten-maven-plugin:1.3.0': java.util.NoSuchElementException
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: org.codehaus.mojo:flatten-maven-plugin:1.3.0:clean
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.3.0:clean (flatten.clean) on pro
ject cloud-fastpaypc: Execution flatten.clean of goal org.codehaus.mojo:flatten-maven-plugin:1.3.0:clean failed: Unable to load the mojo 'clean' (or one
of its required components) from the plugin 'org.codehaus.mojo:flatten-maven-plugin:1.3.0'
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:339)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:322)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:172)
at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:160)
at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:37)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:106)
at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:190)
at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:208)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution flatten.clean of goal org.codehaus.mojo:flatten-maven-plugin:1.3.0:clean failed:
Unable to load the mojo 'clean' (or one of its required components) from the plugin 'org.codehaus.mojo:flatten-maven-plugin:1.3.0'
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:152)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:334)
... 15 common frames omitted
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'clean' (or one of its required components) from the plugin 'org.co
dehaus.mojo:flatten-maven-plugin:1.3.0'
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:531)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:130)
... 16 common frames omitted
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
role: org.apache.maven.plugin.Mojo
roleHint: org.codehaus.mojo:flatten-maven-plugin:1.3.0:clean
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:497)
... 17 common frames omitted
Caused by: java.util.NoSuchElementException: null
at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:118)
at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:1)
at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:76)
at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:1)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
... 19 common frames omitted
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

related issue [https://github.com/mojohaus/flatten-maven-plugin/issues/330](https://github.com/mojohaus/flatten-maven-plugin/issues/330)

**Comment by gnodet** [comment] 2023-01-13 09:15
Please provide a reproducer, as the short description won't be sufficient to understand what the problem is.

**Comment by meiMingle** [comment] 2023-01-13 09:25
Now the relevant PR has been merged into the main branch of maven, maybe this problem will disappear in the next version of maven  [Restore compatibility with flatten-maven-plugin](https://github.com/apache/maven/pull/947)

**Comment by gnodet** [comment] 2023-01-24 09:31
Closing as a duplicate

**Closed by gnodet** 2023-01-24 09:31 UTC
