### ISSUE TITLE
Failed to load native library on Windows with a Chinese user name

### ISSUE THREAD

**Issue by ToDropBombs** [apache/maven-mvnd#571] opened 2022-01-07 10:34 UTC
mvnd -v
```
Failed to load native library:jansi-2.4.0-16c474bda59fea77-jansi.dll. osinfo: Windows/x86_64
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\??\AppData\Local\Temp\jansi-2.4.0-16c474bda59fea77-jansi.dll
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.fusesource.jansi.internal.CLibrary.isatty(I)I [symbol: Java_org_fusesource_jansi_internal_CLibrary_isatty or Java_org_fusesource_jansi_internal_CLibrary_isatty__I]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at org.fusesource.jansi.internal.CLibrary.isatty(CLibrary.java)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:92)
```

java -version:
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
D:\mvnd-0.7.1-windows-amd64\conf\mvnd.properties :
detail:
```
         java.home=C:\\Program Files\\jdk-11.0.2
         maven.settings=D:\\apache-maven-3.6.1\\conf\\settings.xml
```

How should we deal with it?

**Comment by gnodet** [comment] 2022-01-07 10:44
Could you run `java -jar D:\mvnd-0.7.1-windows-amd64\mvn\lib\ext\jansi-2.4.0.jar` and report the output ?

**Comment by ToDropBombs** [comment] 2022-01-07 10:45
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ToDropBombs** [comment] 2022-01-10 01:52
PS D:\> java -jar D:\mvnd-0.7.1-windows-amd64\mvn\lib\ext\jansi-2.4.0.jar
Jansi 2.4.0

library.jansi.path=
library.jansi.version=
Jansi native library loaded from C:\Users\大米\AppData\Local\Temp\jansi-2.4.0-4ad7fea7eb28539c-jansi.dll
   which was auto-extracted from jar:file:/D:/mvnd-0.7.1-windows-amd64/mvn/lib/ext/jansi-2.4.0.jar!/org/fusesource/jansi/internal/native/Windows/x86_64/jansi.dll

os.name= Windows 10, os.version= 10.0, os.arch= amd64
file.encoding= GBK
java.version= 11.0.2, java.vendor= Oracle Corporation, java.home= C:\Program Files\jdk-11.0.2

jansi.graceful=
jansi.mode=
jansi.out.mode=
jansi.err.mode=
jansi.colors=
jansi.out.colors=
jansi.err.colors=
jansi.passthrough= false
jansi.strip= false
jansi.force= false
jansi.noreset= false
org.fusesource.jansi.Ansi.disable= false

IS_WINDOWS: true
IS_CONEMU: false
IS_CYGWIN: false
IS_MSYSTEM: false

isatty(STDOUT_FILENO): 1, System.out is a terminal
isatty(STDERR_FILENO): 1, System.err is a terminal

Resulting Jansi modes for stout/stderr streams:
  - System.out: AnsiPrintStream{type=VirtualTerminal, colors=Colors16, mode=Default, resetAtUninstall=true}
  - System.err: AnsiPrintStream{type=VirtualTerminal, colors=Colors16, mode=Default, resetAtUninstall=true}
Processor types description:
  - Native: Supports ansi sequences natively
  - Unsupported: Ansi sequences are stripped out
  - VirtualTerminal: Supported through windows virtual terminal
  - Emulation: Emulated through using windows API console commands
  - Redirected: The stream is redirected to a file or a pipe
Colors support description:
  - Colors16: 16 colors
  - Colors256: 256 colors
  - TrueColor: 24-bit colors
Modes description:
  - Strip: Strip all ansi sequences
  - Default: Print ansi sequences if the stream is a terminal
  - Force: Always print ansi sequences, even if the stream is redirected

test on System.out: BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE DEFAULT
            bright: BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE DEFAULT
              bold: BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE DEFAULT
             faint: BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE DEFAULT
        bold+faint: BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE DEFAULT
        256 colors:





         truecolor: /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
                    /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
                    /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
                    /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
                    /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
                    /\/\/\/\/\/\/\/\
test on System.err: BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE DEFAULT
            bright: BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE DEFAULT
              bold: BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE DEFAULT
             faint: BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE DEFAULT
        bold+faint: BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE DEFAULT
        256 colors:





         truecolor: /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
                    /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
                    /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
                    /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
                    /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
                    /\/\/\/\/\/\/\/\

                      ┌──┐┌─────┐ ┌─────┐ ┌──────┬──┐
                      │██├┘█████└┬┘█████└┬┘██████│?▌│
                 ┌──┐ │██│██▄▄▄██│██┌─┐██│██▄▄▄▄ │▄▄│
                 │??└─┘?█│?█┌─┐?█│?█│ │?█│ ?????█│?█│
                 └┐▓▓▓▓▓┌┤▓▓│ │▓▓│▓▓│ │▓▓│?▓▓▓▓▓?│▓▓│
                  └─────┘└──┘ └──┴──┘ └──┴───────┴──┘

> Could you run `java -jar D:\mvnd-0.7.1-windows-amd64\mvn\lib\ext\jansi-2.4.0.jar` and report the output ?

**Comment by gnodet** [comment] 2022-01-10 07:14
This is very weird as your first report indicates the jansi library cannot be loaded or does not find the `isatty` function, but the second indicates that it works.  The `mvnd` invocation always fail and the `jansi` call always work or does it depend on the terminal used (cmd, powershelgl, git bash, ... )?

**Comment by 710850609** [comment] 2022-01-13 05:48
> This is very weird as your first report indicates the jansi library cannot be loaded or does not find the `isatty` function, but the second indicates that it works. The `mvnd` invocation always fail and the `jansi` call always work or does it depend on the terminal used (cmd, powershell, git bash, ... )?


I found that the mvnd.exe startup did not recognize the path containing Chinese.
Use mvnd. CMD to start normally


I now use the scheme: rename mvnd.exe (CMD command will identify the MVND command execution file according to the environment variable as mvnd.cmd)

**Comment by gnodet** [comment] 2022-01-13 07:18
> > This is very weird as your first report indicates the jansi library cannot be loaded or does not find the `isatty` function, but the second indicates that it works. The `mvnd` invocation always fail and the `jansi` call always work or does it depend on the terminal used (cmd, powershell, git bash, ... )?
> 
> I found that the path containing Chinese was not recognized when `mvnd.exe` started. `mvnd.cmd` can be used normally.
> 
> The scenario I'm using now is to rename `mvnd.exe` to another name (the CMD command will identify the `mvnd` command execution file as `mvnd.exe` based on the environment variable)

So the problem is when the `mvnd.exe` is in a directory which contains Chinese characters or when the `pom.xml` is in a directory which contains Chinese characters ?

**Comment by 710850609** [comment] 2022-01-13 10:06
> > > This is very weird as your first report indicates the jansi library cannot be loaded or does not find the `isatty` function, but the second indicates that it works. The `mvnd` invocation always fail and the `jansi` call always work or does it depend on the terminal used (cmd, powershell, git bash, ... )?
> > 
> > 
> > I found that the path containing Chinese was not recognized when `mvnd.exe` started. `mvnd.cmd` can be used normally.
> > The scenario I'm using now is to rename `mvnd.exe` to another name (the CMD command will identify the `mvnd` command execution file as `mvnd.exe` based on the environment variable)
> 
> So the problem is when the `mvnd.exe` is in a directory which contains Chinese characters or when the `pom.xml` is in a directory which contains Chinese characters ?
> 
> It would be nice to be able to reproduce the problem.



> > > This is very weird as your first report indicates the jansi library cannot be loaded or does not find the `isatty` function, but the second indicates that it works. The `mvnd` invocation always fail and the `jansi` call always work or does it depend on the terminal used (cmd, powershell, git bash, ... )?
> > 
> > 
> > I found that the path containing Chinese was not recognized when `mvnd.exe` started. `mvnd.cmd` can be used normally.
> > The scenario I'm using now is to rename `mvnd.exe` to another name (the CMD command will identify the `mvnd` command execution file as `mvnd.exe` based on the environment variable)
> 
> So the problem is when the `mvnd.exe` is in a directory which contains Chinese characters or when the `pom.xml` is in a directory which contains Chinese characters ?
> 
> It would be nice to be able to reproduce the problem.

Reproducible conditions are:
The Window OS login user name is in Chinese

**Comment by 18311836573** [comment] 2022-02-07 06:52
I have the same problem，run `java -jar D:\mvnd-0.7.1-windows-amd64\mvn\lib\ext\jansi-2.4.0.jar` That's the same output

**Comment by ToDropBombs** [comment] 2022-02-07 06:52
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by gnodet** [comment] 2022-02-21 15:47
Looks like it's caused by https://github.com/adoptium/temurin-build/issues/1496 and has been fixed with https://bugs.openjdk.java.net/browse/JDK-8240823 in JDK 11.0.8

Please upgrade the JDK.

**Closed by gnodet** 2022-02-21 15:47 UTC

**Comment by shichunyuez** [comment] 2024-09-06 18:54
When I encountered this problem, I found the **installation directory of Maven**. Replace D:\apache-maven-3.9.5\lib\jansi-2.4.0.jar with the lower version of **jansi-1.18.jar**.then it works.

将maven的安装目录中\lib\jansi-2.4.0.jar替换成较低版本的jansi-1.18.jar.然后就不报错了.

![image](https://github.com/user-attachments/assets/d9ca69a8-b34e-4a2f-bcd0-546f6eec628c)

**Comment by ToDropBombs** [comment] 2024-09-06 18:54
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shichunyuez** [comment] 2024-09-06 19:02
After replacement, no error was reported.
![image](https://github.com/user-attachments/assets/e0fd4592-8824-4183-8068-14176ac328c4)

**Comment by 908028664** [comment] 2025-05-13 14:52
由于window11 c盘 用户名 是中文 导致的，可以按照网上的教程，将中文改成英文，即可。

**Comment by ToDropBombs** [comment] 2025-05-13 14:53
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
