### ISSUE TITLE
clean fails cause of locked files

### ISSUE THREAD

**Issue by benbrummer** [apache/maven-mvnd#611] opened 2022-03-22 11:32 UTC
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:3.1.0:clean (default-clean) on project de.emsw.gosa.shared: Failed to clean project: Failed to delete C:\Users\benjamin\Desktop\git\gosa\shared\de.emsw.gosa.shared\target\de.emsw.gosa.shared-1.0.0-SNAPSHOT.jar -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:3.1.0:clean (default-clean) on project de.emsw.gosa.shared: Failed to clean project: Failed to delete C:\Users\benjamin\Desktop\git\gosa\shared\de.emsw.gosa.shared\target\de.emsw.gosa.shared-1.0.0-SNAPSHOT.jar
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:274)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:196)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to clean project: Failed to delete C:\Users\benjamin\Desktop\git\gosa\shared\de.emsw.gosa.shared\target\de.emsw.gosa.shared-1.0.0-SNAPSHOT.jar
        at org.apache.maven.plugins.clean.CleanMojo.execute(CleanMojo.java:210)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:271)
        ... 11 common frames omitted
Caused by: java.io.IOException: Failed to delete C:\Users\benjamin\Desktop\git\gosa\shared\de.emsw.gosa.shared\target\de.emsw.gosa.shared-1.0.0-SNAPSHOT.jar
        at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:251)
        at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:193)
        at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:160)
        at org.apache.maven.plugins.clean.Cleaner.delete(Cleaner.java:118)
        at org.apache.maven.plugins.clean.CleanMojo.execute(CleanMojo.java:189)
        ... 13 common frames omitted
```
`mvnd --status` shows one idle daemon, after `mvnd --stop` clean works again

**Comment by benbrummer** [comment] 2022-03-22 11:39
![image](https://user-images.githubusercontent.com/24470839/159473334-03c65715-3f75-4e40-9cb0-75ce33b6d390.png)
This time stopping mvnd does not unlock the files

**Comment by benbrummer** [comment] 2022-03-22 11:41
![image](https://user-images.githubusercontent.com/24470839/159474015-31b270cd-3b3f-42b5-b2cf-60bdde897ab4.png)
Looks like it is still running

**Comment by benbrummer** [comment] 2022-03-22 11:43
After killing the process files can be deleted

**Comment by ppalaga** [comment] 2022-03-22 16:47
This looks like a duplicate of #115 that was fixed, but the fix is not available in a release yet. Please feel free to reopen, if you feel this issue is different.

**Closed by ppalaga** 2022-03-22 16:47 UTC

**Comment by popcristianvlad** [comment] 2023-10-11 17:58
Just tested with mvnd version 1.0-m7/m39 (maven 3.9.3) on windows and the problem persists.

**Comment by ppalaga** [comment] 2023-10-23 12:22
> Just tested with mvnd version 1.0-m7/m39 (maven 3.9.3) on windows and the problem persists.

Would you mind creating a new issue with a minimal reproducer?
