### ISSUE TITLE
Add arm64 linux support

### ISSUE THREAD

**Issue by pennytextures** [apache/maven-mvnd#1211] opened 2024-11-29 12:59 UTC
It's great that you have Darwin arm64 support, but my own and many other projects have a containerised build, so we need a linux arm64 build.

**Comment by gnodet** [comment] 2024-11-30 07:18
> It's great that you have Darwin arm64 support, but my own and many other projects have a containerised build, so we need a linux arm64 build.

The benefits of the native build are mostly a few milliseconds gained when booting the client. 
We can only provide binaries for platforms supported by GraalVM and for which GitHub provides runners.
Using the Java client will still bring you most of the daemon benefits.

**Comment by ppalaga** [comment] 2024-11-30 08:06
Duplicate of https://github.com/apache/maven-mvnd/issues/921
Some additional info in https://github.com/apache/maven-mvnd/issues/888

**Closed by ppalaga** 2024-11-30 08:06 UTC
