### ISSUE TITLE
java.lang.NoSuchMethodError: 'org.apache.maven.execution.MavenExecutionRequest org.apache.maven.execution.MavenExecutionRequest.setIgnoreTransitiveRepositories(boolean)'

### ISSUE THREAD

**Issue by Hepengzhou** [apache/maven-mvnd#1124] opened 2024-09-03 11:04 UTC
...why 
![image](https://github.com/user-attachments/assets/0bce6c02-1ff3-4e42-8e79-f66bae7c46ae)

**Comment by ppalaga** [comment] 2024-09-03 11:06
Why so many issues for a single problem?

**Comment by ppalaga** [comment] 2024-09-03 11:07
Duplicate of https://github.com/apache/maven-mvnd/issues/1123

**Closed by ppalaga** 2024-09-03 11:07 UTC
